# Generated by Django 6.0.4 on 2026-04-26 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasksmodel_creationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksmodel',
            name='completed',
        ),
    ]
